---
- name: Change env vars
  ansible.builtin.lineinfile:
    path: "{{ nginx.work_dir }}/.env"
    regexp: "^NGINX_PM_PORT"
    line: "NGINX_PM_PORT={{ nginx_pm.port }}"

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ nginx_pm.work_dir }}"