---
- name: Change env vars
  ansible.builtin.lineinfile:
    path: "{{ vcenter.work_dir }}/.env"
    regexp: "^NGINX_PORT"
    line: "NGINX_PORT={{ vcenter.port }}"

- name: Start docker compose file
  ansible.builtin.command: docker compose up -d
  environment:
    VCENTER_PORT: "{{ vcenter.port }}"
  args:
    chdir: "{{ vcenter.work_dir }}"